name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: hotel_staff_db
          MYSQL_USER: root
        options: >-
          --health-cmd="mysqladmin ping" --health-timeout=10s --health-interval=5s

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Clean build directory
        run: mvn clean

      - name: Wait for MySQL
        run: |
          sleep 10
          mysqladmin ping -h 127.0.0.1 -u root -ppassword

      - name: Build and run tests with Maven
        run: mvn verify